---
# Set the base box
base_box: ubuntu/trusty64

# Box Settings
hostname: georgeff

ip_address: 192.168.35.10

memory: 1024

cpus: 1

doc_root: /vagrant/www/public

# Default Timezone
timezone: America/Chicago

# PHP Settings
php:
   version: php5-5.6

# MySQL Settings
mysql:
   root_password: password
   user: mike
   password: password
   database: georgeff

# Git Config
git_name: Mike Georgeff
git_email: mikegeorgeff3@gmail.com